theme = "modus_operandi"

[editor]
line-number = "relative"
mouse = true
auto-completion = true
auto-save = true
auto-format = true
text-width = 80
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
soft-wrap.enable = true
soft-wrap.max-indent-retain = 80
bufferline = "always"
true-color = true

[editor.file-picker]
hidden = false

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.normal]
C-l = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
C-k = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ./.run"
C-j = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% --close-on-exit -- zsh"
